### PR TITLE
Plotting script for global map

### PR DESCRIPTION
**Pull request by seunguk-2**
Uploading Jupyter notebook I used to create the global map

### CODE REVIEW

**Review by Peter9192 — COMMENTED** [review]
This is an awesome figure! I like the Robinson projection 😃 

Now it only uses 2ldrm data. Would it be possible to update it such that it plots the mean of all methods? Note that you can use the data reading function from combine_data.py.

**Comment by chrisweij** [comment]
Great plot, will create an issue so that we do not forget to add the other methods.

**Comment by seunguk-2** [comment]
I will try to create the plot with the mean of all methods. That combine_data.py script was super helpful reading the data, and it will make this way easier.

**Comment by Peter9192** [comment]
> I will try to create the plot with the mean of all methods. That combine_data.py script was super helpful reading the data, and it will make this way easier.

Just a heads up that @apalarcon also started working on this: https://github.com/WAM2layers/Moisture_tracking_intercomparison/pull/74

**Pull request merged**
