### PR TITLE
plot correlation matrix

### PR DESCRIPTION
**Pull request by duetschm**

### CODE REVIEW

**Review by Peter9192 — APPROVED** [review]
Looks good.

Just a suggestion: I was thinking this could also be interesting: https://seaborn.pydata.org/examples/structured_heatmap.html

**Comment by chrisweij** [comment]
Another thing we discussed is that we only have to use the upper right (or lower left) triangle since the correlation matrix is symmetric. 

We could this use the other triangle for e.g. the correlation matrix of the fractional sources..

**Review by chrisweij — APPROVED** [review]

**Comment by duetschm** [comment]
Do you expect a different result for the correlation of the fractional sources? I would expect the same, but maybe I'm not thinking correctly. :)

**Comment by chrisweij** [comment]
@duetschm I think you are correct, I was in doubt first but in principle it is only a constant factor per method/simulation so that I would not change the correlation. 

However, we could probably still think if we can plot something different in the lower triangle since we have the space.

**Comment by duetschm** [comment]
Ok, thanks! Yes I think that's a good idea, we just have to come up with something meaningful.

**Pull request merged**
