### PR TITLE
Updated global map plotting scripts

### PR DESCRIPTION
**Pull request by seunguk-2**
PlateCarree and Robinson projections are used to depict three cases on a global map. Also tried to use absolute and relative.

### CODE REVIEW

**Review by iris-thu — APPROVED** [review]
Thanks for these new plots!

**Comment by seunguk-2** [comment]
> Love these plots. Two comments:
> 
> One of the plots seems to have a different colormap (algea) It seems some 'Scottish' moisture shows up near the Pakistan case. Is that correct?

Thank you!
In response to your comments, the use of different colormaps was intentional. I choose similar but different colormaps for standard deviations to compare with the original colormaps used for the averages. This was to see which colormap would better represent the text and avoid confusion.
Additionally, I find one or a few models from the Scotland case have values extending over the Pacific. By decreasing the low-value threshold, some values overlap near the Pakistan case.

**Comment by Imme1992** [comment]
I like these plot a lot as well, it provides a nice overview directly, and the colorbars are well chosen. Would it be possible to make the colorbars with the (absolute) standard deviation until the same maximum as the absolute numbers? That would make is a bit easier to judge for which precipitation case there is the largest spread in terms of standard deviation.

**Comment by seunguk-2** [comment]
Sure! I will update the plots with standard deviation soon.

**Pull request merged**
