### PR TITLE
Plots showing method differences

### PR DESCRIPTION
**Pull request by victoriademan**
The functions for the plots are those showing the standard deviation, coefficient of variation, absolute method differences and differences from the method mean. I know not all of the plots are meant to be used, but I just kept everything here in case it's interesting for in the exploring phase (of the results)

### CODE REVIEW

**Review by chrisweij — APPROVED** [review]
Looks great, thanks for making these plots.

**Review by duetschm — APPROVED** [review]
Very nice, thanks! The notebook could make use of the new plot_single_map function in Functions.py in the future, then it doesn't have to define the settings for each plot separately.

**Comment by Peter9192** [comment]
Just wondering if this notebook was run with the latest version of the data?

**Comment by victoriademan** [comment]
> Just wondering if this notebook was run with the latest version of the data?

Yes, it should be. Nevertheless, I just downloaded the data again to double-check and found that the "read_flexpart_tatfancheng" gave an error, it seems that the newly uploaded files (less than a day ago) are named differently, so this should be changed in the combine_data file

**Pull request merged**
