### PR TITLE
convert into function and add new datasets

### PR DESCRIPTION
**Pull request by duetschm**

### CODE REVIEW

**Review by victoriademan — APPROVED** [review]

**Review by iris-thu — APPROVED** [review]

**Comment by Peter9192** [comment]
Nice work! Are you still making changes or can I have a go at it in the train? @duetschm @iris-thu @victoriademan

**Comment by victoriademan** [comment]
Hi! We also wanted to add the Scotland and Australia case, but for now, you can have a go at it as we're wrapping up here

**Comment by Peter9192** [comment]
Okay, on my way, see you at the dinner!

**Comment by Peter9192** [comment]
See #45

**Pull request merged**
